### ISSUE TITLE
UserWarning when run dbrestore 

### ISSUE THREAD

**Issue by rgaiacs** [django-dbbackup/django-dbbackup#231] opened 2016-12-12 11:17 UTC
When I run

~~~
$ python manage.py migrate && python manage.py loaddata fixtures/demo.json && python manage.py dbbackup && rm db.sqlite3 && python manage.py dbrestore
~~~

I got a few `UserWarning` on the `dbrestore` phase such as

1.

   ~~~
   /home/raniere/anaconda3/envs/fat/lib/python3.5/site-packages/dbbackup/db/sqlite.py:73: UserWarning: Error in db restore: no such table: main.auth_group_permissions
     warnings.warn("Error in db restore: {}".format(err))
   ~~~

2. 

   ~~~
   /home/raniere/anaconda3/envs/fat/lib/python3.5/site-packages/dbbackup/db/sqlite.py:73: UserWarning: Error in db restore: index auth_group_permissions_group_id_0cd325b0_uniq already exists
     warnings.warn("Error in db restore: {}".format(err))
~~~

The `dbrestore` phase looks to be successful even with the `UserWarning`. Can we solve the `UserWarning`?

**Comment by davidfokkema** [comment] 2017-04-23 13:17
+1

**Comment by ZuluPro** [comment] 2017-05-07 22:54
In fact, the problem is DBBackup tries to create tables again.
It will be solved with a several new options:
- Drop before restore
- Do not save tables

**Comment by jonathan-s** [comment] 2020-12-13 23:40
As we have a reply here I'm going to close this.

**Closed by jonathan-s** 2020-12-13 23:40 UTC
Labels: bug, restore, sqlite
