### ISSUE TITLE
Remove bespoke logging configuration

### ISSUE THREAD

**Issue by racitup** [django-dbbackup/django-dbbackup#270] opened 2017-10-19 10:48 UTC
I would recommend removing the application's own bespoke logging configuration in favour of prefixing the logger name with "django." so that the builtin django logging defaults are used.

You could leave the existing logging config for django < 1.9 since there was a significant change to [the defaults](https://docs.djangoproject.com/en/1.9/_modules/django/utils/log/).

Having to administer an application where every sub-app has it's own logging config is a nightmare.

**Comment by jonathan-s** [comment] 2020-09-20 21:29
Closing as a duplicate of #332

**Closed by jonathan-s** 2020-09-20 21:29 UTC
Labels: Prio, question
