### ISSUE TITLE
Add support for rsync and scp (From `/TODO.md`)

### ISSUE THREAD

**Issue by ZuluPro** [django-dbbackup/django-dbbackup#85] opened 2015-08-06 19:20 UTC
https://github.com/django-dbbackup/django-dbbackup/blob/5bb44b8a7ca4ae4bb973a88b44cf938431a88795/TODO.md

**Comment by benjaoming** [comment] 2015-08-09 09:06
Dupe of #86

**Closed by benjaoming** 2015-08-09 09:06 UTC
