### ISSUE TITLE
Django import ugettext_lazy fails it should be import gettext_lazy 

### ISSUE THREAD

**Issue by zwiebelslayer** [django-dbbackup/django-dbbackup#416] opened 2022-01-04 11:00 UTC
DBBackup imports "from django.utils.translation import ugettext_lazy as _" which fails and throws an ImportError.
by changing the line in apps.py to
 from django.utils.translation import gettext_lazy as _ 
everything works as expected

**Comment by johnthagen** [comment] 2022-01-04 12:51
Duplicate of #399 closed in #342

Please try the `4.0.0b0` release on PyPI (#415).

**Closed by johnthagen** 2022-01-04 12:51 UTC
Labels: duplicate
